version: "3.8"
volumes:
  db-store:
  php-fpm-socket:
services:
  app:
    build: ./.docker/php
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - .:/app/sinoalice

  web:
    build: ./.docker/nginx
    ports:
      - 8000:80
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - .:/app/sinoalice

  db:
    build: ./.docker/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 3306:3306
